#
#  Makefile
#

ifndef INITRD_DIR
    INITRD_DIR = $(PWD)/../initrd_tmp
    export INITRD_DIR
endif

all:
	cd pkgutil; make $@

install:
	cd pkgutil; make $@

env:
	cd pkgutil; make $@

clean:
	cd pkgutil; make $@
